### ISSUE TITLE
[Security] Full site takeover via POST request

### ISSUE THREAD

**Issue by alexanderpas** [musicman3/eMarket#9]
Sending a specifically crafted post request to `controller/catalog/pages/success/index.php` allows for a full site takeover, since `/model/eMarket/Install/Success.php` blindly writes away the config without any form of verification upon a well formed POST request.

I urge you to review the most common pitfalls https://owasp.org/www-project-top-ten/ as well as the current PHP best practices on https://phptherightway.com/ before starting anything related to e-commerce, as this project is full of security holes and bad practices detrimental for security.

**Comment by musicman3** [comment]
Hello. What does controller / catalog / pages / success / index.php have to do with it?
and
/model/eMarket/Install/Success.php from installation?
The Install folder should be made unavailable after installation. Please write in detail. The project has POST / GET / SERVER validation, there is also filtering for XSS and LFI. In addition, prepared queries for PDO are used. If you are sure about the problem, please write how to cause it so that you can make a correction. I don't see the problem at the moment.

**Comment by alexanderpas** [comment]
I aplogize for any confusion.

`controller/install/success.php` calls `eMarket\Install\Success()` directly.

https://github.com/musicman3/eMarket/blob/5cbede1b9b034b24eec52888be8bb43152b54633/controller/install/success.php#L12

The constructor in `eMarket\Install\Success` calls `eMarket\Install\Success->config()`, which creates the config file contents, with any missing values replaced with false.

Afterwards `eMarket\Install\Success` constructor calls `eMarket\Install\Success->save()`, which writes away the config file to disk as `/storage/configure/configure.php` without any further validation.

**Comment by musicman3** [comment]
This is the Install directory. It is removed after installation. Read here - https://github.com/musicman3/eMarket/wiki/Installation

**Comment by alexanderpas** [comment]
> This directory must be removed after installation.

This is unlikely to happen, as there is no check for this status, and there is no mention of this CRITICAL SECURITY REQUIREMENT in the main README for this project.

A better way to secure against this issue is to check if there is no config file is created, and if a config file has been created, to only allow installation if a specific variable has been set in the config file. This way it also becomes safe to include the install.php file in version control.

**Comment by musicman3** [comment]
> A better way to secure against this issue is to check if there is no config file is created, and if a config file has been created, to only allow installation if a specific variable has been set in the config file. This way it also becomes safe to include the install.php file in version control.

Thanks. Checking for a config file is a good idea. This is easy to do. In the near future, I will be setting up a routing for install, which will check for the presence of a config file. If this file is on the server, then the installation will not be possible.
